### ISSUE TITLE
Uncaught TypeError: Cannot set property type of #<HTMLSelectElement> which has only a getter

### ISSUE THREAD

**Issue by etaque** [elm-lang/virtual-dom#10]
In Elm 0.18:

```elm
import Html exposing (..)
import Html.Attributes exposing (..)

main =
  select [ type_ "checkbox" ] []
```

It's a user mistake (`select` tags should not have a `type` attribute) that provokes a runtime error.

---

*Edit: I updated the above for 0.18. Below is the original report, for Elm 0.15 -@rtfeldman*

``` elm
import Html exposing (..)
import Html.Attributes exposing (..)

main =
  select [ type' "checkbox" ] []
```

**Comment by evancz** [comment]
Does this happen in 0.16 as well? If so, what do you propose as the fix?

**Comment by etaque** [comment]
Doesn't happen with 0.16, I discovered my mistake in [this package](https://github.com/etaque/elm-simple-form) while migrating it to 0.17 (it wasn't triggering any runtime error in 0.16)

**Comment by evancz** [comment]
It looks like the new and old libraries are doing *exactly* the same things. As far as I can tell, both are doing:

```javascript
var node = createElement('select');
node['type'] = 'checkbox';
```

I guess something is happening in between those two things. I looked at all the fields in `node` and there are definitely fewer in the new one. I don't really understand how or why.

**Comment by etaque** [comment]
That could be related to strict mode and browser versions, I'm investigating.

**Comment by etaque** [comment]
See here:
http://www.ecma-international.org/ecma-262/5.1/#sec-11.13.1 (NOTE section)

**Comment by rtfeldman** [comment]
This still throws a runtime exception in 0.18. I updated OP to reflect this.

**Comment by evancz** [comment]
Tracking in #106 which is for any `type_` issues.

Please continue discussion here if there is more information to share. The point of the meta issue is to do some organizing and editorializing that makes it easier to make progress on this sort of thing.

**Comment by gege251** [comment]
It is an even sillier mistake on my part, but I accidentally left a `class` attribute from Html.Attributes in an svg element. I am using 0.19.1.
https://ellie-app.com/7xG7sn9nrB2a1
