### ISSUE TITLE
Debugger controls can get covered by application elements

### ISSUE THREAD

**Issue by lzrski** [elm-lang/virtual-dom#100]
Migrating from https://github.com/elm-lang/elm-make/issues/168 as asked by @avh4 

In the browser the Elm Debugger controls (introduced in 0.18 with `elm-make --debug` flag) can easily be covered by the application elements, e.g. if they have position `absolute`. A case of that bug is discussed in https://github.com/debois/elm-mdl/issues/270.

I believe this should be solved by changing the setup of Elm debugger instead of  each particular library / application.

Minimal example:

```elm
module Trolololo exposing (main)

import Html exposing (div, text)
import Html.Attributes exposing (style)


main =
    div
        [ style
            [ ( "position", "absolute" )
            , ( "width", "100%" )
            , ( "height", "100%" )
            , ( "z-index", "1" )
            ]
        ]
        [ text "Try to debug me! Trolololo." ]
```

**Comment by lukewestby** [comment]
Tracking in #98
