### ISSUE TITLE
domNode.elm_event_node_ref is undefined in Internet Explorer 11, Edge (early versions) 

### ISSUE THREAD

**Issue by BumbrT** [elm-lang/virtual-dom#101]
Reproducing in IE11 and early versions of Edge. Chrome, Safari, Firefox, latest Edge not affected.
Elm 0.18  
 "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/dom": "1.1.1 <= v < 2.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
I tried to build minimum reproduction example, but can't catch this bug.
So i can only reproduce it as a part of large project.
App stops handling events from element, because eventNode is undefined, so click event does not propagates.

Here is my research in source code
http://take.ms/hjwox
http://take.ms/ckJmn
I have no idea how to build smaller example, maybe you can help me with suggestion

UPD: Found WA with using Html.Keyed.node, maybe it can be usefull for someone. I think this makes VDOM merges less complicated.

**Comment by BumbrT** [comment]
Found WA with using Html.Keyed.node, maybe it can be usefull for someone.

**Comment by evancz** [comment]
I am tracking all of the `VirtualDom.map` ideas in #105 so that it is clearer how to make coherent changes.

I'll close here, cleaning up the issue queue. The idea is that this content is all available for reference, but easier for me to find. Point is, thanks for the report!

**Comment by evancz** [comment]
Separately, is this a problem with development builds of IE? Or is it a problem with actually released browsers?

**Comment by BumbrT** [comment]
Reproducing bug in the latest version of IE11 11.413.15063.0
Latest edge behaves correctly.
I can easily reproduce issue in my project. I will try to create  SSCCE  later

**Comment by allenap** [comment]
@cachar and I were able to workaround this, and @lukewestby previously too, by separating the `Html.map` from the problematic view code by wrapping it in a div:

i.e. from:

```elm
viewSomething : Html OtherMsg

viewBiggerThing : Html Msg
viewBiggerThing =
  div [] [ Html.map BiggerOtherMsg viewSomething ]
```

to:

```elm
viewSomething : Html OtherMsg

viewBiggerThing : Html Msg
viewBiggerThing =
    div [] [ Html.map BiggerOtherMsg <| div [] [ viewSomething ] ]
```
