### ISSUE TITLE
Remember the opened state for the elm debugger for nested records stored inside dicts

### ISSUE THREAD

**Issue by AionDev** [elm-lang/virtual-dom#102]
I would like to keep the debugger state opened between messages. Better see this: 
![debugger is closing when for opened dicts](https://user-images.githubusercontent.com/20288140/27751241-06440616-5de4-11e7-86f2-3c1b59d76b33.gif)

The first layer is kept open between updates - but more nested than that no - is not working width `dicts`. 
Every time i click on a message - what i selected previously is collapsed.

For this project makes more sense to use `Debug.log` calls for everything then to open this ( 3-4 clicks deep) on each update.  Pretty annoying..

And when stuff is more nested makes more sense to have the debugger backing you. Hope this can be done -  i have no idea how to actually do this :smile:

**Comment by evancz** [comment]
Tracking in #98. Thank you for the report and helpful visuals on the problem!
