### ISSUE TITLE
Debugger issues

### ISSUE THREAD

**Issue by blunderdome** [elm-lang/virtual-dom#111]
@lukewestby suggested I put this here; hope that's OK.

* On some pages there are two debugger panels, of different sizes, overlaying each other. One of them also has a lower z-index than some other page elements -- you can see it disappear and reappear as the page scrolls.

![elvt051yy1](https://user-images.githubusercontent.com/4333625/28976515-261c5518-790c-11e7-9805-d7cc29584650.gif)

* On another page, the width of the debugger changes when a checkbox is checked / unchecked (causing a table to be added to / removed from the page).

![7danb7ktbm](https://user-images.githubusercontent.com/4333625/28976610-94e13fae-790c-11e7-8f1e-146427eac9bd.gif)

The debugger also isn't recording anything here, but I think that may be expected because parts of the page aren't in Elm.

**Comment by lukewestby** [comment]
@blunderdome thanks! tracking in #98

**Comment by avh4** [comment]
(Note that on the pages where this happens, we are embedding two separate elm apps on the same page)
