### ISSUE TITLE
Function equality in Lazy

### ISSUE THREAD

**Issue by gdotdesign** [elm-lang/virtual-dom#13]
Right know functions cannot be used in the `Html.Lazy` bacause it throws a runtime error: 
`Equality error: general function equality is undecidable, and therefore, unsupported`

To put this in context, consider the following example:

```elm
-- Component
type Msg 
  = Click

type alias Context msg =
  { mouseDownMsg : msg }

view : (Msg -> msg) -> Context msg -> Model -> Html.Html msg
view address context model =
   div 
    [ onClick (address Click) 
    , onMouseDown context.mouseDownMsg
    ]


-- Parent
type Msg
  = Component Component.Msg
  | Click

view : Model -> Html.Html Msg
view model =
  Component.view 
    Component
    { mouseDownMsg = Click } 
    model.component
```

This is a straightforward way of making components that can have messages from the parent or to have content that comes outside of them.

This is essentially the same as `Signal.forwardTo` was, and the problem with that was that in every iteration a new function was created and made lazy useless, but in this case the generally functions are static and only created once.

This function comparison wasn't a problem in 0.16 because it was comparing **identity** not **equality**.

Having functions compared by **identity** is OK in my opinion, and it would solve this problem, however I understand the logic behind this change but having a cryptic runtime error is bad and it takes some time to find where it's coming from.

**Comment by jvoigtlaender** [comment]
> Right know functions cannot be used in the `Html.Lazy` bacause it throws a runtime error:
> `Equality error: general function equality is undecidable, and therefore, unsupported`

What is a concrete (minimal, possibly artificial) piece of Elm 0.17 code involving `Html.Lazy` that throws this runtime error?

**Comment by gdotdesign** [comment]
I'll try to make an SSCCE.

**Comment by jvoigtlaender** [comment]
Having looked into the issue a bit more, I would actually be *surprised* by any such example. I don't see how you can possibly get the error in your first comment from the current `Html.Lazy` implementation. Are you sure that not something unrelated was going on in your problematic case?

(If there were indeed a problem with function equality, https://github.com/elm-lang/core/pull/213 might be a solution. But as just said, I'm skeptical of your report now. `Html.Lazy` isn't, as far as I can tell, even using the kind of equality check that would lead to the error you mention.)

**Comment by gdotdesign** [comment]
Yes, that's the code I ran into (which throws this error) and the trigger is using lazy rendering instead of normal, but the cause is not in **html** or **core** but in **elm-community/elm-list-extra** https://github.com/elm-community/elm-list-extra/blob/1.0.0/src/List/Extra.elm#L263, basically I try to find the index of a lazy function in a list, which should work if we were comparing **indentity**.

**Comment by jvoigtlaender** [comment]
Actually, `==` *is* always first comparing identity. For any function `f`, the test `f == f` evaluates to `True`. But that indeed does not help you if you want to find `f` in the list `[g, f]` by subsequent comparisons. Because the test `f == g` will throw a runtime error.

But all that is really not an issue of `html` or `virtual-dom`. So I think it does not make sense to have this issue open here. Instead, it is an issue of `core`, and your `Html.Lazy` use is "just" a motivating example for wanting `f == g` not throw a runtime error. You could add that to the discussion at https://github.com/elm-lang/core/pull/213 and/or https://github.com/elm-lang/elm-compiler/issues/1145.

**Comment by gdotdesign** [comment]
Yeah you are right, I'll add this case for the issues, but I have a question then, **lazy nodes** are not comparable with regular **nodes** or both are functions and that's is the why?

**Comment by jvoigtlaender** [comment]
I'm sorry, I don't understand the question. And if it's about deep internals of the implementation of `virtual-dom`, I'm probably not the right person to answer it. Your comment further above indicated that the problem you had was with calls of `==` on functions stored in a list, as part of a call to `List.Extra.elemIndex`. This has nothing to do with `Html.Lazy`. When the `lazy` functions from `Html.Lazy` compare stuff, they do it with JavaScript's `===` operator. Which on functions is exactly checking *identity* of the function objects.

**Comment by gdotdesign** [comment]
I was wondering about the internals, why for example these nodes `div [] []`, `Html.Lazy.lazy div [] []` are not comparable. I close this now and will comment on one of the issues.

**Comment by jvoigtlaender** [comment]
I still suspect that something unrelated was actually happening for you. I just tried this:
```elm
import Html exposing (div)
import Html.Lazy

main = Html.text (toString (div [] [] == Html.Lazy.lazy2 div [] []))
```
It does *not* throw a runtime error. It gives the answer `False`. So the two nodes *are* comparable.
