### ISSUE TITLE
DOM mutations are not the same depending on code syntax

### ISSUE THREAD

**Issue by pauldijou** [elm-lang/virtual-dom#14]
Not sure if this is a bug or not, but depending on the code syntax, the resulting DOM is the same but not the mutations to render it.

Mostly, having `Html.App.map` inside a `Maybe.withDefault` will result on removing and adding a new node while having `Maybe.withDefault` inside `Html.App.map` will result on editing the node attributes and changing the text inside it.

Here is a repo reproducing the issue https://github.com/pauldijou/elm-dom-diff

IMO, since the final virtual DOM is the same, it should probably apply the same patch / mutation events.

**Comment by evancz** [comment]
Can you get this down to an http://sscce.org? Ideally just a gist that I can compile with `elm-make` or run in elm-lang.org/try

**Comment by pauldijou** [comment]
Sure thing. Here is the code you can copy/paste into elm-lang.org/try to reproduce the problem: https://gist.github.com/pauldijou/10251ce38646f473d5a689731c68d126

(you can no longer see DOM mutations inside the console... but I put the JS code to display them at the end of the Gist if you need it)

**Comment by evancz** [comment]
Tracking in #105. Thank you for the report!
