### ISSUE TITLE
Documentation for attributeNS does not identify the parameters

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/virtual-dom#15]
`attributeNS` takes three parameters -- the namespace, the key and the value.

However, the documentation does not indicate which parameter is which.

Of course, one can read the native code to find out that the first parameter is the namespace, the second the key, and third the value. Also, it is probably the logical order for the parameters -- at least, it is the order I would have expected. Nevertheless, it might be helpful to some users to indicate in the documentation which parameter is which.

(Note that the documentation for `attribute` also does not formally indicate which parameter is the key and which is the value. However, the documentation gives an example for `attribute` which makes it pretty obvious).

**Comment by evancz** [comment]
I added docs to this effect at some point in a recent batch of changes. Should be clearer now, and should be out with the next release!
