### ISSUE TITLE
TypeError: domNode.elm_event_node_ref is undefined

### ISSUE THREAD

**Issue by colinmccabe** [elm-lang/virtual-dom#2]
https://gist.github.com/colinmccabe/56abf3c8a602834401cac1933c38ba7f

The program above results in a `TypeError: domNode.elm_event_node_ref is undefined` exception on this line: https://github.com/elm-lang/virtual-dom/blob/1.0.0/src/Native/VirtualDom.js#L914

It has something to do with this code that returns either a div or a table from a case and then (pointlessly) feeds the result into `Html.App.map`.

```elm
view : Model -> Html.Html Msg
view model =
  let html =
    case model of
      [] ->
        Html.div [] [ Html.text "No items, displaying div with text" ]

      xs ->
        viewTable xs
  in
    Html.App.map (\_ -> NoOp) html

viewTable : Model -> Html.Html a
viewTable model =
  Html.table ...
```

Removing the case so that `html` is always a table or removing `Html.App.map` makes the exception go away.

Interestingly, virtual-dom successfully renders the table on the first tick, and the exception occurs on the second tick.

**Comment by evancz** [comment]
If you get rid of your `elm-stuff/` and rebuild, you should see that it works now. Thanks for the report!

**Comment by noobymatze** [comment]
Hi, 

I am sorry, but something along these lines still breaks for me in IE 11 in this line: https://github.com/elm-lang/virtual-dom/blob/1.1.1/src/Native/VirtualDom.js#L1306 (problem being an undefined `elm_event_node_ref`). A minimal breaking example can be found here: https://gist.github.com/noobymatze/9b80606ccc69ad05e9b368b31532cc03

Typing any two letters into the rendered input element will result in the mentioned exception and removing `App.map` and changing the resulting type to `Html Msg` will resolve that.

I am not sure about anything below IE 11, but IE Edge, Chrome, Firefox and even Safari 5.1.7 (on Windows) and Opera seem all to be working fine.

**Comment by evancz** [comment]
Please open a new issue about this!
