### ISSUE TITLE
Preserve cursor position in contentEditable elements

### ISSUE THREAD

**Issue by ajhyndman** [elm-lang/virtual-dom#23]
I can't find reference to any relevant changes in the rewrite which have resolved this issue: https://github.com/evancz/virtual-dom/issues/24

I wonder if a pleasant API for handling this scenario might be a function like this?

`innerHtml : Html -> Attribute msg`

Then you could define children as standard elm-lang/html elements, but under the hood, set the content of the contenteditable div using the DOM's `Element.innerHTML` API, which will allow us to preserve the cursor position.

**Comment by iqualfragile** [comment]
Is there something i can do to make this happen? This is an important usecase for me.

**Comment by ajhyndman** [comment]
I was keen to try implementing a generic composable WYSIWYG editing experience in Elm as well.  This seems to me to be a prerequisite.

**Comment by evancz** [comment]
I am consolidating all `contenteditable` stuff into #104, so we can see it all in one place.

Thanks for the report!

**Comment by ajhyndman** [comment]
For clarification, the objective here was to preserve cursor positions within a contenteditable element, when its content changes.

It just so happens that browsers can do this when the diff is reconciled via an `innerHtml` call, but not if the DOM nodes themselves are removed and replaced.

I'm not sure if I'm explaining this well.
