### ISSUE TITLE
Absence of 'contenteditable' causes runtime error (cannot handle 'null' as a value)

### ISSUE THREAD

**Issue by digital-ember** [elm-lang/virtual-dom#27]
Hello,
I found this to be a problem in other virtual dom implementation while I was searching for a solution. Not certain if this really needs fixing here.

Elm-version: 0.17.0
Browser: Chrome Version 51.0.2704.84 m

## GIST
if a node with "contenteditable" set is meant to be updated and the new node does not have this property, I get the following error:

> Uncaught SyntaxError: Failed to set the 'contentEditable' property on 'HTMLElement': The value provided ('null') is not one of 'true', 'false', 'plaintext-only', or 'inherit' 

![contenteditable](https://cloud.githubusercontent.com/assets/19651078/16649195/12b4232a-4438-11e6-8507-c231c5ced9a5.png)

Fails in Edge as well, cannot test Firefox right now.

## REPRO
Try out the following Elm example that toggles between a div with contenteditable set to True and one with no contenteditable attribute.

```Elm
import Html exposing (..)
import Html.Events exposing (..)
import Html.Attributes exposing (..)
import Html.App as Html

type alias Model = 
  { content : String
  , editable : Bool 
  }

type Msg = ToggleContentEditable

main = 
  Html.beginnerProgram
    { model = { content = "Hello", editable = False }
    , view = view
    , update = update 
    }

update msg model =
  case msg of
    ToggleContentEditable -> 
      {model | editable = (not model.editable)}

view model =
  div []
    [ Html.button [onClick ToggleContentEditable] [ text "Toggle" ]
    , viewContent model
    ]

viewContent model =
  if (model.editable)
  then div [contenteditable True] [ text model.content ]
  else div [ ] [ text model.content ]
```

Setting contenteditable explicitly to "False" in the alternative div resolves this problem.
However, in my use case, I have an app with several tabs (similar to the elm-mdl demo page), where I have a contenteditable div in one tab, and a completely different subtree to render another div, so I don't know how I should set contenteditable explicitly in this different subtree.

**Comment by evancz** [comment]
Can you make the title something that summarizes the problem better?

**Comment by digital-ember** [comment]
Let me know if this title is better or let me know if you have something specific in mind. 
Thank you.

I found this discussion on another virtual-dom implementation that seems related: https://www.bountysource.com/issues/7948850-diff-and-patching-nodes-with-contenteditable-inherit

**Comment by evancz** [comment]
If you set this attribute using `attribute "contenteditable" "true"` does the problem persist?

If it is resolved by using `attribute` this will be fixed by https://github.com/elm-lang/html/pull/54

**Comment by digital-ember** [comment]
Using ```attribute "contenteditable" "true"``` resolves this issue. Thanks.
Let me know if you need me to close this once #54 is merged.

**Comment by evancz** [comment]
Great, I am going to close then, folks can track the fix. Thanks for the issue and detailed description!
