### ISSUE TITLE
Events handlers attached in the wrong place

### ISSUE THREAD

**Issue by evancz** [elm-lang/virtual-dom#3]
https://gist.github.com/lukewestby/3dc48266b15a4837a79ddd71e58c6999

**Comment by evancz** [comment]
Hey @lukewestby and @eeue56, I figured out the fix in 1278bc8b0f995771bb7c71caf6893af8b325a43c and moved the tag, so if you clear out `elm-stuff/` and rebuild the issue should go away. (As well as some related issues people had not observed yet.)

**Comment by lukewestby** [comment]
Neat! Thank you!
