### ISSUE TITLE
type Node msg = Node

### ISSUE THREAD

**Issue by co-dh** [elm-lang/virtual-dom#30]
This is just a question.
I don't understand this line:
type Node msg = Node
in virtual-dom. 
I am not able to find any document on this also.
Can you answer the question and please update the document ( syntax part)

**Comment by evancz** [comment]
This is a trick I pull in some platform libraries, definitely not for general use. It means there is a type `Node` with only one constructor, also named `Node`. In normal code, this would be a supremely unhelpful definition. In this library, we need to express certain things in JS to hook up to the DOM, so we need to create a type to call those things. Elm does not allow definitions like `type Node msg` but that is basically what we are doing. Just creating the type of a thing that's represented in a very special way for very special reasons.
