### ISSUE TITLE
Trouble initially setting some JS properties

### ISSUE THREAD

**Issue by cobalamin** [elm-lang/virtual-dom#31]
When using `Html.Attributes.property` to set some properties, it doesn't work on the first render. The example property is `scrollTop`, which has no effect on the first render, but works fine after the DOM node was inserted.

[Example code here](https://gist.github.com/cobalamin/6a5e009df6dcf53817030b4a4a226ecb)

I'm reporting this here since `elm-lang/html` isn't at fault, it just shows the problem easily.

---

I understand [why this is happening](https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L273-L274) – we're calling `render` first, which calls `applyFacts`, and only then inserting the node into the DOM. At the point when `applyFacts` is called, the element doesn't overflow yet, so setting `scrollTop` will have no effect and reset to `0`.

This can be further demonstrated for example by changing [line 371](https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L371) like so, which makes the example work on the initial render as well:

```js
// for attributes that can and should be set before the node is inserted
applyFacts(domNode, eventNode, vNode.facts);
// for attributes that have to be set after the node is in the DOM
setTimeout(function() {
    applyFacts(domNode, eventNode, vNode.facts);
}, 0); 
```

_Side note: More terrible things can be done with `property` that totally break Elm, like `property "innerHTML" (Json.string "borked!")` -- then the indexing of the nodes that actually should be inserted doesn't work anymore and Elm does odd things or breaks._ I don't know what should be done with this, `property` is an unsafe escape hatch anyways.

Still, I consider this to be a bug, as someone was just bitten by it in the #beginners channel on Slack and it takes a while to figure out why this is happening and I don't know how to work around it in plain Elm.

**Comment by masimun** [comment]
I can replicate this issue, and thanks for making it a good description!

**Comment by evancz** [comment]
I believe the functionality you want will be covered by [this](https://groups.google.com/forum/#!topic/elm-dev/ThkWudq7SF0). The fact that you can mess with this should be added to [this](https://groups.google.com/forum/#!topic/elm-dev/DZK12PVzGAo).

I believe those cover everything here, so I will close.
