### ISSUE TITLE
VirtualDom.keyedNode may produce incorrect reordering of children

### ISSUE THREAD

**Issue by justinmimbs** [elm-lang/virtual-dom#32]
This [example](https://gist.github.com/justinmimbs/fa580fabd39ba4e3f53d84dd5357863c) renders the same list of numbers twice; once using `node` and once using `keyedNode`. There are buttons to let you select one of two orderings for the list. Initially, both `node` and `keyedNode` render the list the same, but when you click the second button to change the order, you see that `keyedNode` renders the list in the wrong order.

**Comment by evancz** [comment]
Great job with the http://sscce.org/! I'll see if I can track this one down!

**Comment by evancz** [comment]
That was a pretty tricky one, but I believe it should be sorted out now. Thanks again for the excellent SSCCE!

**Comment by justinmimbs** [comment]
Nice! That looked like a tricky one. You'll also need to pass `patch` to the new function though, so it can use it [here](https://github.com/elm-lang/virtual-dom/blob/fe2d24caf4fa9c2b69ab80d8c53dd01cf7eddc82/src/Native/VirtualDom.js#L1424).

No problem on the SSCCE! Thanks for the excellent language and tools! ;)

**Comment by evancz** [comment]
Ah, thanks for catching that. I wish there was some kind of compiler to catch stuff like that :P

**Comment by evancz** [comment]
Okay, this fix should be released in elm-lang/virtual-dom 1.1.1. Thanks again!
