### ISSUE TITLE
Diffing seems to break when requestAnimationFrame is called from a port

### ISSUE THREAD

**Issue by benbotwin** [elm-lang/virtual-dom#34]
It doesn't look like elm diffs text when I call `requestAnimationFrame` from a port and the next view's dom is the same structure.

For example, If I try rendering `example` then use a port that calls `requestAnimationFrame` then 
change the view to `broke` it'll keep all the text from `example` and just add the new text.

```
example : Model -> Html Msg
example model =
    pre [ onClick (Next Broke), id "elm" ]
        [ code []
            [ text """
module Main exposing (..)
import Html exposing (Html, div, text)
main : Html a
main =
  """
            ]
        ]


broke model =
    pre [ onClick (Next StepBack), id "elm" ]
        [ code []
            [ text """
module Main exposing (..)
import Html exposing (Html, div, text)
main : Html a
main =
  div [] [ text "Hello, World" ]
  """
            ]
        ]
```

An example of what it looks like in an app:
https://github.com/thecodethinker/elm-presentation/tree/broken

**Comment by evancz** [comment]
I do not feel there is enough information here to make a fix. What are you doing in the `requestAnimationFrame` call? Is it touching the DOM in a particular way?

If you can get this down to an http://sscce.org/ that displays the bug with the latest release, please open a new issue.
