### ISSUE TITLE
selected checkboxes 'stick' when removed

### ISSUE THREAD

**Issue by maxf** [elm-lang/virtual-dom#37]
[Apologies if repeat or invalid bug or wrong repo]

The code at https://gist.github.com/maxf/efd173cf14a77f4af381cf8ad4c13a20 has a basic List String model and turns it into a ul with checkboxes for each string in the model, as so:

![image](https://cloud.githubusercontent.com/assets/69542/19267996/b8042f5c-8fa9-11e6-879e-be943b96756d.png)

There's also a message that lets the user remove items by clicking the relevant checkbox. For instance, when clicking on the 3rd item, it removes  "three"  from the model and view renegerates the Html:

![image](https://cloud.githubusercontent.com/assets/69542/19268038/f81c3b3e-8fa9-11e6-9c67-28673dc1cb0b.png)

As you can see the 3rd checkbox is now ticked. But clearly shouldn't.

**Comment by jvoigtlaender** [comment]
This is what the [Html.Keyed](http://package.elm-lang.org/packages/elm-lang/html/latest/Html-Keyed) module is for. If you can't figure out how to use it to avoid the issue you describe, please ask on Slack or on the mailing list.

http://elm-lang.org/community

**Comment by jvoigtlaender** [comment]
Note that while the documentation of that module just says "... to reuse nodes more efficiently", it's really not just about efficiency, but also about correctness, as in your case.

**Comment by maxf** [comment]
Thanks for the workaround @jvoigtlaender
Indeed, it's about correctness here.

**Comment by jvoigtlaender** [comment]
Why do you not close the issue here?

**Comment by jvoigtlaender** [comment]
To the point, what I indicated is not a workaround. It is the API you have to use for what you want to do.

**Comment by maxf** [comment]
I'm not sure how this is not a bug. The tick mark appears on an checkbox I didn't interact with.
Using an external package to get the correct behaviour is indeed a workaround, not a fix, in my opinion.

**Comment by OvermindDL1** [comment]
@maxf This is because keyed will cause node regeneration, if you just (from the perspective of the virtualdom) change the text and even handler it does not know that it needs to reset any possible user state of it without knowing that the underlying model changed, which is exposed via keyed.  It is technically the same checkbox just mutated with the new data, keyed tells it that it is an entirely new checkbox.

**Comment by jvoigtlaender** [comment]
How is elm-lang/html an "external package"? It's the same package you are using, and Keyed is the proper API for your use case. 

But I won't argue further here. I mentioned before that if you need discussion of this, the place for that discussion is not here. Slack or the mailing list us it. In fact, if you check the mailing list archive, you are bound to find several threads around this already.

**Comment by maxf** [comment]
@jvoigtlaender ; you're right, it's not an external package. But my point stands, and I've started a discussion at https://groups.google.com/forum/#!topic/elm-discuss/ZZQvfFLpzPE
