### ISSUE TITLE
Attribute unexpectedly removed after a change

### ISSUE THREAD

**Issue by gdotdesign** [elm-lang/virtual-dom#4]
While trying to reproduce an other bug I ran into this one: https://gist.github.com/gdotdesign/cc924f6e591efec979524fe643ee5c12, it renders fine at the first pass but after a change the **style attribute** gets removed.

Steps to reproduce
* after clicking on the div the style attribute is removed

Expected behavior:
* after clicking on the div the color should change to red

I used the latest version.

**Comment by evancz** [comment]
Seems to be resolved with #6 fix as well. Confirm?

**Comment by gdotdesign** [comment]
Yes, it works.
