### ISSUE TITLE
[alpha] unicode triangles do not render properly on Mac OS X using Chrome or Safari

### ISSUE THREAD

**Issue by pragmaticstudio** [elm-lang/virtual-dom#40]
Using the --debug flag with "elm make", and then clicking the "Explore History" tab, the unicode triangles aren't rendering properly in the following environment:

Mac OS X 10.11.6 
Safari 10.0
Chrome 54.0.2840.59 
Elm 0.18.0

![screen shot 2016-10-17 at 3 34 44 pm](https://cloud.githubusercontent.com/assets/65799/19459193/77097ec8-948e-11e6-8d7a-5fd69d9a8269.png)

**Comment by evancz** [comment]
Are you using a custom monospace font? They should be the characters ▸ ▾ … which all appear fine for me in macOS in Chrome and Safari.

**Comment by clarkware** [comment]
Ah, it turns out both Safari and Chrome were using a default encoding of "Western". Switching both to "Unicode (UTF-8)" solved the problem. Strange thing is I have no idea why "Western" was the default encoding. I don't recall changing it, and I can't remember a time when I saw these sorts of encoding issues in my browser. I wonder how many other folks are using "Western" as the default encoding...

**Comment by jinjor** [comment]
![2016-10-22 23 38 02](https://cloud.githubusercontent.com/assets/2568148/19620127/eb637406-98b0-11e6-8181-c052969c11b8.png)

My Chrome on macOS Sierra seems to use monospace but... they looks like Mario blocks.

**Comment by OvermindDL1** [comment]
Might want to specify one of the google fonts for a typeface for drawing those, that should work around that issue regardless of platform (unless a very old IE 8 or something, in which case it would just fall back to the system fonts anyway).

**Comment by evancz** [comment]
@OvermindDL1, don't want a font dependency. It'd need to be distributed with vdom to work offline.

@clarkware, do any of the arrows [here](http://www.w3schools.com/charsets/ref_utf_geometric.asp) show up okay on your computer?

Otherwise, it's probably best to use [this trick](https://css-tricks.com/snippets/css/css-triangle/) or figure out a way to do it with SVG.

**Comment by clarkware** [comment]
@evancz Yes, all of those triangles render properly regardless if I set the browser to use UTF-8 or Western encoding! So that might be the way to go...

**Comment by evancz** [comment]
Hmm, I thought I was using one of them... Is there some way to know exactly what unicode character you are getting as is?

Also, how do you switch between UTF-8 and Western encoding? Do you have a link so I can see it too?

**Comment by clarkware** [comment]
In Chrome, go to View -> Encoding and you can select a specific encoding. If I select Unicode (UTF-8), then the unicode triangles in the debug pane render properly. But if I select Western (which was my default for some reason), then they don't render properly. However, the triangles [here](http://www.w3schools.com/charsets/ref_utf_geometric.asp) render properly whether I use Unicode or Western encoding.

Does that help?

**Comment by evancz** [comment]
Thanks for showing me how to change the encoding! The change *appears* to fix things on my machine, and we can know for sure when the next round of binaries come out. If there are any other open alpha issues, point them out to me. It'd be great to get that all done before the next round!

**Comment by clarkware** [comment]
Hmm... I'm still seeing funky characters in the beta. Strangely, changing the encoding to UTF-8 in Chrome doesn't fix it. I wonder if this is something specific to my machine. I'll continue investigating...

**Comment by clarkware** [comment]
Ah - fixed it! I had to set the charset in my index.html:

```html
<meta charset="UTF-8">
```

Sorry for the false alarm!

**Comment by evancz** [comment]
No worries. Yeah, if it's going through `elm-reactor` it should work by default, but if you are doing your own thing, I'm not sure how to fix that. It may sometimes be necessary to add a charset to the actual script tag, like I had to for the reactor. Maybe there's a better solution, but I couldn't figure out how to do those tricky arrows in the right sizes.
