### ISSUE TITLE
Runtime error from clearing contenteditable DIV

### ISSUE THREAD

**Issue by chancyk** [elm-lang/virtual-dom#48]
Windows 7
Chrome 54.0.2840.71

I see the following in the Chrome console after clearing the text from a `contenteditable True` DIV. An example that reproduces the problem is included at the bottom of this comment.

![image](https://cloud.githubusercontent.com/assets/1731217/20198638/4a65d53e-a76b-11e6-98cd-0a5492e550af.png)

which points to the following snippet from `applyPatch`:

```javascript
function applyPatch(domNode, patch)
{
	switch (patch.type)
	{
		case 'p-redraw':
			return applyPatchRedraw(domNode, patch.data, patch.eventNode);

		case 'p-facts':
			applyFacts(domNode, patch.eventNode, patch.data);
			return domNode;

		case 'p-text':
			domNode.replaceData(0, domNode.length, patch.data);
			return domNode;
```

Example
---------
Clear the text in either DIV to reproduce the error.

```elm
{-| This code reproduces the error in issue https://github.com/elm-lang/virtual-dom/issues/48 -}

import Html exposing (text)
import Html.App as App
import Html.Attributes exposing (contenteditable)
import Html.Events exposing (on)
import Json.Decode as Json


type Msg = HelloUpdate String | WorldUpdate String

update msg model =
  case msg of
    HelloUpdate txt ->
      ( { model | hello = txt }, Cmd.none )

    WorldUpdate txt ->
      ( { model | world = txt }, Cmd.none )

initModel =
  { hello = "hello"
  , world = "world"
  }

view model = 
  Html.div 
    []
    [ Html.div
        [ contenteditable True
        , onInput HelloUpdate
        ]
        [ text model.hello ]
    , Html.div 
        [ contenteditable True
        , onInput WorldUpdate
        ]
        [ text model.world ]
    ]

onInput msg = 
  on "input" (Json.map msg innerHtmlDecoder)

innerHtmlDecoder =
  Json.at ["target", "innerHTML"] Json.string


main =
    App.program
        { init = (initModel, Cmd.none)
        , update = update
        , view = view
        , subscriptions = (\_ -> Sub.none)
        }
```

**Comment by chancyk** [comment]
I spent some time trying to figure out what was going on here and it seems like the fundamental cause of the issue is that Chrome is actually removing the `text` DOM element when the text is cleared through `contenteditable`, so when the virtual DOM is recursing over the nodes from [here](https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L1177), it ends up passing an empty list as `childNodes` instead of the `text` element that it was originally expecting. 

The `p-text` patch ends up trying to replace the data with an empty string, but the node no longer exists and thus the property error when it tries to access the `replaceData` function on the undefined element.

**Comment by chancyk** [comment]
My code seems to behave when I place an undefined check on the p-text case of [applyPatch](https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L1244), but is this is a sufficient fix?

From:
```elm
case 'p-text':
    domNode.replaceData(0, domNode.length, patch.data);
    return domNode;
```

To:
```elm
case 'p-text':
    if (domNode !== undefined){
        domNode.replaceData(0, domNode.length, patch.data);
    }
    return domNode;
```

**Comment by AppSynergy** [comment]
I've got the same error in a fairly different context, in fact it's hard for me to see how they're related, so thanks for this!

It's not limited to Chrome - Firefox gives a more helpful message:

**TypeError: domNode.replaceData is not a function [Learn More](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type)**

which points to something similar to what you've got, though maybe it should be `typeof domNode` instead.

The patch above resolves my instance nicely, but I can still break your SSCE. e.g: 

````
<div contenteditable="true"><div><br></div>Broken now</div>
````
will break the app (even with #51)

Different browsers create different html structures in contenteditables for the same input, which I don't like at all. I suspect the whole thing might be haunted.

**Comment by chancyk** [comment]
@AppSynergy That's a good point. My use case is strictly text but I guess you can cram whatever you want into `contenteditable` elements. 

I suspect the easy fix may just be to detect the `contenteditable` property and always issue a `p-redraw` on those elements, and just disregard the diffing of the children.

**Comment by chancyk** [comment]
Pull request https://github.com/elm-lang/virtual-dom/pull/51 only address the case where the `contenteditable` element contains a single text element, which may not even be treated consistently across browers.

A blanket redraw on `contenteditable` elements doesn't behave properly, as a redraw removes the focus and cursor from that element, which makes it impossible to actually edit the element. These seem to be some of the choices available for a more comprehensive fix:

1. Check the entire child tree of the actual DOM to determine elements haven't vanished, and that it's safe to apply patches as normal, otherwise redraw.
2. Treat `contenteditable` elements as volatile and disregard its children in the virtual DOM, always redrawing the `contenteditable` elements and their children.
3. Fully re-index `contenteditable` elements every pass into the virtual DOM.
4. Have patches "succeed" when the DOM node doesn't actually exist by checking for undefined `domNode` where necessary.
5. Consider this feature haunted and possibly advise the use of actual `input` elements instead.

**Comment by evancz** [comment]
I am consolidating all `contenteditable` stuff into #104, so we can see it all in one place.

Thanks for the report!
