### ISSUE TITLE
Debugger is broken for the webgl examples that contain textures

### ISSUE THREAD

**Issue by w0rm** [elm-lang/virtual-dom#50]
When the native debugger wants to serialize an object with `{ctor: 'RawTexture', img: img}` the image [is considered to be a record here](https://github.com/elm-lang/virtual-dom/blob/master/src/Native/Debug.js#L225), and this causes `Uncaught RangeError: Maximum call stack size exceeded`.

The representation of the texture is either `{ ctor: 'RawTexture', img: img }` or `{ ctor: 'Texture', img: img }`, https://github.com/elm-community/webgl/blob/master/src/Native/WebGL.js#L38

The type is `Texture`: https://github.com/elm-community/webgl/blob/master/src/WebGL.elm#L89

I can fix it by putting an image into a getter `function () { return img; }`, then it will be serialized as `XXX`. Not sure if this solution is acceptable.

**Comment by evancz** [comment]
I wouldn't want to go that route if it has a performance penalty in practice. If it does, it's probably better to detect when something is an image and do something else.

**Comment by w0rm** [comment]
@evancz the textures [are cached by id](https://github.com/elm-community/webgl/blob/master/src/Native/WebGL.js#L409), so there is no real performance penalty.

**Comment by w0rm** [comment]
I will be watching this issue, in the meantime I'm going to merge a fix into webgl, just to not be blocked. 

It's an internal change that may be reverted any time.
