### ISSUE TITLE
Debugger expand-arrows can break when the charset is not "utf-8"

### ISSUE THREAD

**Issue by AnimiVulpis** [elm-lang/virtual-dom#52]
Not really a bug, only a thing I ran into by accident (and others might too 🙄 )
(using the `--debug` flag for `elm-make` in `elm 0.18.0`):

When embedding an elm-app into a html page with no

    <meta charset....

defined the debugger showed me `â–¸` and `â–¾` instead of `▸` and `▾`

The fix was simply to specify

    <meta charset="utf-8">

In the `<head>` of the html document.

----

I apologize if this is not the right place to mention this and would ask for instructions/information on where to place/post this.

**Comment by evancz** [comment]
Tracking in #98. Thanks for the report!
