### ISSUE TITLE
IE9: "Unexpected draw callback."

### ISSUE THREAD

**Issue by maxf** [elm-lang/virtual-dom#55]
See screenshot. The message appears when loading hello-world in IE9 (emulated).
![elm-ie9](https://cloud.githubusercontent.com/assets/69542/20438341/2b277dfe-adaf-11e6-8411-8606d63bee39.png)

**Comment by wizza-smile** [comment]
Same error occurs on the original iPad 1 as soon as the first Msg is being send to update.

`module Main exposing (..)

import Html exposing (..)
import Html.Events exposing (..)


main =
    Html.program
        { init = init
        , view = view
        , update = update
        , subscriptions = always Sub.none
        }


type Msg
    = TestMsg


init =
    {} ! []


view model =
    div [ onClick TestMsg ] [ text "HELLO WORLD" ]


update msg model =
    model ! []`

**Comment by tracker-common** [comment]
We are having this issue to, in our CI, which means we cannot update to Elm 18 until it gets resolved  :( :(

As far as we can tell, the problem has something to do with a combination of our ci linux (Trusty Tahr) and our headless browser (phantomjs phantomjs-prebuilt@2.1.13).

We are able to run it everywhere else (non linux) using the same phantom version with no problems.

```
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).
     
       Error: Unexpected draw callback.
       Please report this to <https://github.com/elm-lang/virtual-dom/issues>.
       Error: Unexpected draw callback.
       Please report this to <https://github.com/elm-lang/virtual-dom/issues>.
           at http://localhost:5101/assets/dashboard_v2-bundle.js:10505 in updateIfNeeded
           at http://localhost:5101/assets/dashboard_v2-bundle.js:10490
           at http://localhost:5101/assets/dashboard_v2-bundle.js:10529 in stepper
           at http://localhost:5101/assets/dashboard_v2-bundle.js:2506
           at http://localhost:5101/assets/dashboard_v2-bundle.js:3143 in step
           at http://localhost:5101/assets/dashboard_v2-bundle.js:3198 in work
     # /usr/local/bundle/gems/poltergeist-1.7.0/lib/capybara/poltergeist/browser.rb:335:in `command'
     # /usr/local/bundle/gems/poltergeist-1.7.0/lib/capybara/poltergeist/browser.rb:61:in `find'
     # /usr/local/bundle/gems/poltergeist-1.7.0/lib/capybara/poltergeist/driver.rb:120:in `find'
     # /usr/local/bundle/gems/poltergeist-1.7.0/lib/capybara/poltergeist/driver.rb:124:in `find_xpath'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/node/base.rb:107:in `find_xpath'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/query.rb:110:in `block in resolve_for'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/node/base.rb:80:in `synchronize'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/query.rb:106:in `resolve_for'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/node/finders.rb:34:in `block in find'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/node/finders.rb:32:in `find'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/node/document.rb:23:in `text'
     # /usr/local/bundle/gems/capybara-2.5.0/lib/capybara/session.rb:698:in `block (2 levels) in <class:Session>'
```

**Comment by matteosister** [comment]
same problem with chrome 18 on android

**Comment by karls** [comment]
Same problem on IE11 on Windows 10 running inside Virtualbox.

![](http://d.pr/i/Qs5c.png)

**Comment by daymosik** [comment]
Same problem on IE9 on Windows7 inside Virtualbox
![zrzut ekranu 2016-12-16 o 14 50 38](https://cloud.githubusercontent.com/assets/8873967/21264895/0d854366-c39f-11e6-8a80-872d7ed235be.png)

**Comment by witoldsz** [comment]
It happens also in IE 11 emulation document mode: 9
As a bonus, compared to IE9, the 11 gives a full stack trace so it's easier to debug.

![screenshot from 2016-12-17 22-47-48](https://cloud.githubusercontent.com/assets/544581/21289976/e993b462-c4aa-11e6-87c2-609a3f63ad90.png)

**Comment by daymosik** [comment]
Same problem on Android Browser (Android 4.1.2)

**Comment by witoldsz** [comment]
@evancz This issue is becoming so serious in our system (we have replaced old login app with the new one written in Elm few days ago) that there are voices for removing Elm as people are unable to enter our main application.
This bug is serious as nothing works, the whole app freezes.

Question: is there possible workaround?

**Comment by witoldsz** [comment]
After brief testing, it looks like @daymosik solved the issue here: #74.

While @daymosik  was working in that pull-request I was looking for a backup plan and I've found a workaround: the [requestAnimationFrame polyfill library ](https://github.com/chrisdickinson/raf)
You can try it before proper fix is found:

```html
<script src="https://wzrd.in/standalone/raf@latest"></script>
<script>window.raf.polyfill();</script>
```
Add this before your Elm application and it will use the polyfilled `requestAnimationFrame` instead of currently broken fallback.

**Comment by daymosik** [comment]
We can confirm that the workaround that @witoldsz introduced works like a charm, the number of errors went to zero.

**Comment by daymosik** [comment]
So i've made some improvements in my PR in order not to break the elm-repl, but in my PR the code will support some older browsers with prefixed requestAnimationFrame.

**Comment by daymosik** [comment]
@evancz why You did not want the prefixed version ?
