### ISSUE TITLE
Some users cannot use debugger

### ISSUE THREAD

**Issue by jinjor** [elm-lang/virtual-dom#56]
In particular case, `elm-make --debug` generates invalid JavaScript. It causes a runtime error.

```
Uncaught TypeError: Cannot read property 'nativeBinding' of undefined
```

This is because `_elm_lang$virtual_dom$Native_Debug` tries to use `_elm_lang$core$Native_Scheduler` before initialization. This order seems to change according to the user name.

This is NG case. (user name = `ell`)
```json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/ell/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

... and this is OK. (user name = `eln`)
```json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/eln/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

Looks like if the user name is before `elm-lang` the debugger crashes.

To be worse, if this module is published, the project that depends on it cannot use debugger either. I'm using `elm-community/elm-material-icons` and ran into this.

**Comment by w0rm** [comment]
In `Debug.elm` the order of dependencies is the following:

```
import Native.Debug
import Native.VirtualDom
import Task exposing (Task)
```

where `Native.Debug` uses `Native.Scheduler` that is imported with `Task`. Moving the `Task` import before `Native.Debug` seemed to fix this issue for me.

**Comment by w0rm** [comment]
The minimum test case to reproduce:

Main.elm:
```elm
module Main exposing (main)

import Html exposing (Html, text)


main : Html a
main =
    text "a"

```

elm-package.json
```json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        ".",
        "src/"
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-community/html-extra": "2.1.0 <= v < 3.0.0",
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
```

Please note that `elm-package` includes a library from `elm-community` that is not even used. This is essential to trigger the wrong order in the bundle.
