### ISSUE TITLE
Feature request: Diff between history states

### ISSUE THREAD

**Issue by mordrax** [elm-lang/virtual-dom#63]
The full state of my game is quite large and it can be difficult to see what's changed between messages if I didn't know what I was looking for. This isn't a problem most of the time because I know what to look for, but to aid in finding unexpected bugs, it would be great to show the change between two states as well as the full state dump.

![image](https://cloud.githubusercontent.com/assets/4709169/20638985/3d774680-b40b-11e6-9748-aa104ffffda3.png)

This was actually mentioned in another issue: https://github.com/elm-lang/virtual-dom/issues/49#issuecomment-261569572 but I feel it deserves it's own place for discussion.

**Comment by mordrax** [comment]
Well.. I just learned from process-bot after I created this that:

> Issues are for bugs.

So happy for you to close this and I'll take it back to slack/google groups.

**Comment by evancz** [comment]
This is something we'd like to do. @jinjor has something like it in his time travel project, and we have coordinated a bit on merging that into the official debugger. I'd rather not track progress on it in an issue, but hopefully that helps!
