### ISSUE TITLE
Proposal: Functions to mutating node's properties

### ISSUE THREAD

**Issue by bamorim** [elm-lang/virtual-dom#67]
So, today I was creating a flex layout using elm, and turn out that, for flex to work, alot of divs in the three should have flex, so I found myself editing a lot of places and realized there is no way to mutate a Node.

For example, if I want a component renders a div and want to add some styles to that div in diferent contexts, I cant easily. So most of the time I found myself passing styles and children as parameters to my functions just to be able to extend it somewhere, cluttering with empty lists the places where no customization is needed, so I realized:

Why not being able to transform the Node data structure? Maybe with functions like:
```elm
addProperty : Property msg -> Node msg -> Node msg
changeProperty : (String msg -> String msg) -> String msg -> Node msg -> Node msg
addStyles : List (String msg, String msg) -> Node msg -> Node msg
```
It would be really easier to deal with those things without having to add a lot of parameters when there is no need to and without having to create a big DOM tree

What do you guys think?
Maybe I can try to make that work and submit a PR if people are interested in it.

**Comment by lukewestby** [comment]
Hey @bamorim,

It's preferred that proposals like this are shared on [elm-dev](https://groups.google.com/forum/#!forum/elm-dev) so that github issues can be used for tracking bugs and problems. Can you send a message over there with your idea?

**Comment by bamorim** [comment]
Sorry about that @lukewestby.
I'll post that there.

**Comment by lukewestby** [comment]
@bamorim no apology necessary! thanks for understanding :)
