### ISSUE TITLE
Html.map appears to have problems particularly in conjunction with Html.Lazy

### ISSUE THREAD

**Issue by markhamburg** [elm-lang/virtual-dom#73]
Update 31 Dec 2016. I am now pretty certain of what happened in the second case below and I have a reproducible SSCCE attached at the end of this report. The problem stems from an interaction between Html.map nodes and Html.Lazy nodes. In particular, when reviewing the code for `render` in `VirtualDom.js` one sees that in the case of a tagger node, it renders the subside and then sets the `elm_event_node_ref` field on the result to contain the effects of the tagger. A thunk node, on the other hand returns the node that results from evaluating and rendering the thunk. If the result of evaluating the thunk, however, would have had a tagger node at its head, then the resulting DOM node from rendering the thunk will have already had `elm_event_node_ref` set for the tagger inside the lazy and this entry will get stomped. So far, this isn't a problem because all of the tagging works by following the links in the event nodes themselves but when we go to update the event nodes we find them by these links off the DOM nodes and updates that should go to the inner event node instead go to the outer event node. In the case of the SSCCE, we had an initial message chain that looked like:
```
Html.map C <| Html.Lazy <| Html.map D <| Click
```
 and after clicking the button should have gone to:
```
Html.map A <| Html.Lazy <| Html.map B <| Click
```
The update to the inner route, however, gets applied to the outer event node (after the outer update has applied) and so instead leaves us at what is in effect:
```
Html.map B <| Html.Lazy <| Html.map D <| Click
```

This issue explains a large number of occasional problems. It does not appear to explain the first problem I reported where a blur message appears to be delivered via the new message path rather than the old. This could be explained if the blur message fired after it had been removed from the DOM but its event handlers were still in place and hence delivered the message up through the updated event nodes for the new DOM. I have not yet, been able to reproduce that case though a read of the code in VirtualDom.js suggests that it's possible if DOM nodes can fire events after being removed from the DOM. I'll keep working on that one.

----
I don't have a small reproducible case yet. I'm on deadline and distilling things down will come later, but given the bugs I've just worked around, something is wonky with Html.map.

Problem:

Messages from the view are coming back with the wrong tags on them. This seems to be an issue in how Html.map is handled.

The specific examples I've seen:

1. A blur event sent by a text field after it was removed from the DOM propagated up through the event mapping logic that had been updated for the new path. Specifically, there were Html.map nodes in the same position near the top in the old and new view trees but they used different mapping functions. The blur event sent by the text field from the old tree got tagged with the function from the Html.map in the new tree. The eventual result in this case was a crash when code tried to interpret this event. (Every JavaScript programmer's favorite "undefined is not a function" as a matter of fact.) I traced the logic in JavaScript that was doing the tagging and it seemed to be using a chain of event nodes connected to the new tree rather than the old tree. The problem went away when I used Html.Keyed to force the diff logic to see the trees as distinct.

2. I'm less clear on what happened in my second case but in this case messages in views from the new tree seemed to just be skipping one of the Html.map taggers while propagating up. So, again, messages would arrive and fail to dispatch correctly though in this case it wasn't fatal — it just left the UI inoperative. Again pointing to a problem in Html.map, I worked around this by replacing an Html.map usage with passing a tagger function down into the tree to be applied more directly further down.

There was a separate report on elm-discuss that sounded similar to these issues.

When I know more, I will add more.

----

The github uploader doesn't support .elm files so here is the example code:

```elm
module Main exposing (..)

import Html exposing (..)
import Html.Events exposing (onClick)
import Html.Lazy


main =
    beginnerProgram
        { model = model
        , update = update
        , view = view
        }



-- MODEL


type alias Model =
    { state : Bool
    , message : String
    }


model : Model
model =
    { state = False, message = "initial" }



-- MESSAGE


type alias Msg =
    StageMsg (StageMsg BaseMsg)


type StageMsg subMsg
    = A subMsg
    | B subMsg
    | C subMsg
    | D subMsg


type BaseMsg
    = Click



-- UPDATE: Build and check the prefix. Flip the state.


update : Msg -> Model -> Model
update =
    updateStage (updateStage updateBase) ""


updateStage :
    (String -> subMsg -> Model -> Model)
    -> String
    -> StageMsg subMsg
    -> Model
    -> Model
updateStage subUpdate prefix stageMsg model =
    case stageMsg of
        A subMsg ->
            subUpdate (prefix ++ "A") subMsg model

        B subMsg ->
            subUpdate (prefix ++ "B") subMsg model

        C subMsg ->
            subUpdate (prefix ++ "C") subMsg model

        D subMsg ->
            subUpdate (prefix ++ "D") subMsg model


updateBase : String -> BaseMsg -> Model -> Model
updateBase prefix baseMsg model =
    let
        checkedModel =
            checkEpected
                (if model.state then
                    "AB"
                 else
                    "CD"
                )
                prefix
                model
    in
        case baseMsg of
            Click ->
                { checkedModel | state = not checkedModel.state }


checkEpected expected got model =
    if expected /= got then
        { model | message = "Expected " ++ expected ++ ", got " ++ got }
    else
        { model | message = "Expected and got " ++ expected }



-- VIEW: Cascade of maps with a lazy in between


subView_ : Bool -> Html (StageMsg BaseMsg)
subView_ state =
    Html.map
        (if state then
            B
         else
            D
        )
    <|
        Html.button [ onClick Click ] [ text "Click Me!" ]


subView : Bool -> Html (StageMsg BaseMsg)
subView state =
    Html.Lazy.lazy subView_ state


view : Model -> Html Msg
view model =
    div []
        [ text "This program swaps between two routings `AB` and `CD` when you click the button."
        , Html.br [] []
        , text "Click twice to fail."
        , Html.br [] []
        , Html.map
            (if model.state then
                A
             else
                C
            )
          <|
            subView model.state
        , Html.br [] []
        , text <| "Click results: " ++ model.message
        ]
```

**Comment by markhamburg** [comment]
I had it happen again — bad message tagging that went away if I coalesced some Html.map nodes — but sadly my efforts at an SSCE have so far proven unsuccessful. I'm going to look for other avenues to track this down.

**Comment by markhamburg** [comment]
I supplied an SSCCE on Dec 31, 2016. What does it take to get the no SSCCE label removed?

**Comment by justinmimbs** [comment]
Here is a smaller SSCCE of the `Html.Lazy` case.

https://ellie-app.com/3rx74zrKKYha1/0

And here is an SSCCE of the `onBlur` case described above; it fails in Chrome, as Chrome fires a blur event when a focused element is removed from the DOM.

https://ellie-app.com/3rx46YR5s4Da1/0

In both examples, the problem seems to arise when 1) we replace one mapped node with a differently mapped node, such that a [p-tagger patch is applied][1], and 2) the resulting node can still produce its old messages, but it now uses the new tagger.

In both examples, the problem can be avoided by giving the swapped nodes a different number of taggers, which will [force a p-redraw][2] patch instead of a p-tagger patch.

[1]: https://github.com/elm-lang/virtual-dom/blob/2.0.4/src/Native/VirtualDom.js#L1262-L1271
[2]: https://github.com/elm-lang/virtual-dom/blob/2.0.4/src/Native/VirtualDom.js#L625-L631

**Comment by markhamburg** [comment]
Thanks for distilling those issues down and figuring out what was going on in the blur case.

**Comment by evancz** [comment]
I am tracking all of the `VirtualDom.map` ideas in #105 so that it is clearer how to make coherent changes.

I'll close here, cleaning up the issue queue. The idea is that this content is all available for reference, but easier for me to find. Point is, thanks for the report!
