### ISSUE TITLE
Setting div[contenteditable] property makes the code to crash as soon as the div is removed from the app.

### ISSUE THREAD

**Issue by Natim** [elm-lang/virtual-dom#81]
I have this code: https://github.com/mozilla-services/hoverpad/tree/show-elm-bug

It is doing a on blur with a Json.Decode on the innerHtml property. But as soon as you click on Lock, it crashes. Any idea of why?

**Comment by Natim** [comment]
**What OS and browser are you using? What versions?**

Firefox

**What version of Elm are you using?**

elm 0.18

**Comment by Natim** [comment]
I opened the code in chrome and I have a much more explicit message:

```
Uncaught DOMException: Failed to set the 'contentEditable' property on 'HTMLElement': The value provided ('null') is not one of 'true', 'false', 'plaintext-only', or 'inherit'.
```

**Comment by Natim** [comment]
The solution was to keep the div in the page with a `display:none` to fix the issue.

**Comment by simonh1000** [comment]
I got the same error message and fixed it used Html.Keyed

**Comment by evancz** [comment]
I am consolidating all `contenteditable` stuff into #104, so we can see it all in one place.

Thanks for the report!
