### ISSUE TITLE
When using Html.Attributes.property "innerHtml" next events on "blur" or on "input" are not triggered anymore

### ISSUE THREAD

**Issue by Natim** [elm-lang/virtual-dom#82]
When using `Html.Attributes.property "innerHtml"`, events `on "blur"` or `on "input"` are not triggered anymore.

**Browsers:** Firefox and Chrome
**Elm:** 0.18

```
import Html
import Html.Attributes
import Html.Events
import Json.Decode
import Json.Encode


innerHtmlDecoder =
    Json.Decode.at [ "target", "innerHtml" ] Json.Decode.string

view model = 
   Html.div
            [ Html.Attributes.contenteditable True
            , Html.Events.on "blur" (Json.Decode.map SetData innerHtmlDecoder)
            , Html.Attributes.property "innerHTML" (Json.Encode.string model.content)
            ]
            []

```

**Comment by elliotdickison** [comment]
@Natim This is way late, but the problem is that your decoder is failing, so the SetData message is never being routed back to your update function.  Change `innerHtml` to `innerHTML` in your decoder and you should be golden: https://ellie-app.com/RS8GS48Kv4a1/0

**Comment by Natim** [comment]
Thanks :)
