### ISSUE TITLE
force nodes to pair

### ISSUE THREAD

**Issue by ConnyOnny** [elm-lang/virtual-dom#84]
CSS transitions only work when a node in the old DOM is transformed to the matching node in the new DOM. This can be accomplished by introducing a node id (not actually rendered to DOM) that forces nodes to match if that id matches.
Here is a blog post about the problem: https://cberhard.wordpress.com/2017/01/29/elmlang-and-css-transitions/

**Comment by zwilias** [comment]
@ConnyOnny Isn't this essentially what `Html.Keyed` is all about?

**Comment by ConnyOnny** [comment]
Yes it is. Thanks.
