### ISSUE TITLE
Debugger very slow when model contains base64 images

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/virtual-dom#85]
My app requires me to download data that includes base64 image data in it. The strings get shortened to e.g. `picture = "zxcvvbnm...wertyui"` in the debugger view, but opening the debugger still takes a very long time. I'm not sure what exactly would make the difference, but perhaps you could just put `long string` instead of trying to massage the string itself

**Comment by evancz** [comment]
Tracking in #98. Thanks for the report!

Is it just a long `String` in Elm? If not, can you try to make an SSCCE? I need to know the type that's causing the problem.
