### ISSUE TITLE
Copy from /paste to contenteditable causes runtime error

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/virtual-dom#89]
See https://ellie-app.com/tnXL92zwvka1/6

Basically copy-paste copies styles by default. paste therefore adds an extra span with the copied styles. Possible solutions [here](http://stackoverflow.com/questions/12027137/javascript-trick-for-paste-as-plain-text-in-execcommand)

**Comment by evancz** [comment]
I am consolidating all `contenteditable` stuff into #104, so we can see it all in one place.

Thanks for the report!

**Comment by tigp** [comment]
@evancz this still seems to be an issue with `document.execCommand` it's also moving cursor to the start of the field. Do you have plans to improve that in near future?

**Comment by tigp** [comment]
The same with 0.19
