### ISSUE TITLE
Mousedown cancels click in a certain case

### ISSUE THREAD

**Issue by torii-y** [elm-lang/virtual-dom#9]
This happens when a node is inserted before the node that fired "mousedown" event.

* Elm 0.17rc2
* virtual-dom 1.0.0 (after 935b8de)

SSCCE:

```elm
import Html exposing (div, text)
import Html.App exposing (beginnerProgram)
import Html.Events exposing (onMouseDown, onClick)

main =
  beginnerProgram { model = "init", view = view, update = update }

view model =
  div []
    ((if model == "changed" then [ text "" ] else []) ++
    [ div
      [ onClick Click
      , onMouseDown Change
      ] [ text "click me" ]
    , div [] [ text model ]
    ])

type Msg = Change | Click

update msg model =
  case Debug.log "msg" msg of
    Change ->
      "changed"
    Click ->
      "clicked"
```
The first click causes `Change` message but does not cause `Click`. The second click causes the both.

**Comment by torii-y** [comment]
> This happens when a node is inserted before the node that fired "mousedown" event.

For more information, this is not the only case. I ran into this problem in my project, where the DOM event was "dblclick" instead of "click", and the relationship of nodes was parent-children instead of siblings. It was much more complex. I tried to reproduce it in SSCCE but found it too hard.

**Comment by jinjor** [comment]
I tried 0.16 just now. The same problem also happens here. (I thought this was the cause of degradation in my project, but it seems to be another...)

```elm
import Html exposing (div, button, text)
import Html.Events exposing (onMouseDown, onClick)
import StartApp.Simple as StartApp

main =
  StartApp.start { model = "init", view = view, update = update }

view address model =
  div []
    ((if model == "changed" then [ text "" ] else []) ++
    [ div
      [ onClick address Click
      , onMouseDown address Change
      ] [ text "click me" ]
    , div [] [ text model ]
    ])

type Msg = Change | Click

update msg model =
  case Debug.log "msg" msg of
    Change ->
      "changed"
    Click ->
      "clicked"
```

**Comment by evancz** [comment]
My gut is that this is just how HTML works. It's weird, but it's not an Elm thing. If it happens in 0.17 and in 0.16, that kind of confirms this. Will you close this if it is happening in both? Otherwise, what am I not understanding?

**Comment by torii-y** [comment]
Hmm...I think it is particular problem with Virtual DOM. In my hypothesis, a click event listener unlistens right after mousedown event fires, and then new event listener is attached to the same DOM, but it does not share the context with previous one. But I'm not sure if sharing callback function between before and after would cause another problem.

Anyway, I close this issue. It's happening in both 0.16 and 0.17. I will try to find some workaround.

**Comment by vschoettke** [comment]
@evancz This also fixes #12. Any release scheduled?

**Comment by evancz** [comment]
Yes, coming soon.

**Comment by gdotdesign** [comment]
I'm sorry to report this but there is now an other bug probably introduced from the fix of this one (in version 1.0.1).

Event listeners cannot be reattached to an element if that event listener has been removed before:
https://gist.github.com/gdotdesign/b5d0a64523a3e32460f2eec2b1bad484
* The button sets a flag in the model `haveEvent` that corresponds with the event handler (True if attached False if not) and resets the shown text
* Clicking on the "Click Me" text wile having an event handler should update the model to show the "Hello There" text
* At first it works but after removing and reattaching the event handler it doesn't work anymore

A more real world example is here: https://github.com/gdotdesign/elm-ui/blob/0.2/source/Ui/Pager.elm#L103
where the `onTransitionEnd` events are used track the end of a transition and they are removed afterwards.

**Comment by evancz** [comment]
@gdotdesign, open a new issue.

**Comment by gdotdesign** [comment]
You mean next time? I see you already fixed it ;)

**Comment by evancz** [comment]
Yeah :) I ended up looking at this one immediately, but in general, I want to keep issues very focused. The more comments, the harder it is to figure out what's actually broken. So in an ideal world, the original post would have everything.
