### ISSUE TITLE
elm-overlay box unresponsive/covered

### ISSUE THREAD

**Issue by 4ZM** [elm-lang/virtual-dom#91]
The small debug box ends up below the transparent full window pane of the elm-mdl div. No click events get through to the box. Same behavior on latest Firefox and Chromium browsers.

I've experienced this with an elm-mdl app. It might be some particular thing I'm doing with it, but I think it could pop up else where as well.

By hacking in `z-index: 1` in the `.elm-overlay` class everything seems to work again.

**Comment by lukewestby** [comment]
This is also covered by #100, and is being tracked under #98. Thanks!
