### ISSUE TITLE
`class` special case like `className`

### ISSUE THREAD

**Issue by ssbb** [elm-lang/virtual-dom#93]
I am just noticed that `class` (for Svg) is not special cased like  `className`. So with 

`[ Svg.Attributes.class "first-class", Svg.Attributes.class "second-class" ]` I will get second class only. But with `className`:

`[ Html.Attributes.class "first-class", Svg.Attributes.class "second-class" ]` I will get both of them like `"first-class second-class"`.

Is this an expected behavior or `class` should have special case too?

**Comment by evancz** [comment]
This will be fixed in the next release. See https://github.com/elm-lang/virtual-dom/pull/94#issuecomment-313626786 for details. Thanks for the report!
