### ISSUE TITLE
Export from debugger fails erroneously on types that contain magic strings

### ISSUE THREAD

**Issue by jamesmacaulay** [elm-lang/virtual-dom#97]
If your `Msg` type contains a type whose fully qualified name contains within it the name of one of the hardcoded "problem" types, it is treated as unserializable when it shouldn't be. Here is a minimal example that produces an error (when it shouldn't) if you try to export from a debugger session:

https://ellie-app.com/3bJBLXZYFqHa1/2

One of the nested types that needs to be serialized is `GraphQL.Client.Http.RequestError`, and unfortunately that name contains the string `"Http.Request"`, which makes it fail the test here:

https://github.com/elm-lang/virtual-dom/blob/f2350652d4f6fe0bf8c60347c3c7eff8588bbded/src/VirtualDom/Metadata.elm#L119-L140

I think the linked code should be altered to use regular expressions instead of strings in the `problemTable` so that the ordinary named types can be wrapped in beginning-/end-of-string markers, while the function type `"->"` regex could be left alone or perhaps wrapped in word-boundary markers.

**Comment by evancz** [comment]
Tracking in #98. Thanks for the report!
